// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pbc_distances
NumericVector pbc_distances(const NumericMatrix& points, const NumericMatrix& lims);
RcppExport SEXP nspp_pbc_distances(SEXP pointsSEXP, SEXP limsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lims(limsSEXP);
    __result = Rcpp::wrap(pbc_distances(points, lims));
    return __result;
END_RCPP
}
