#' Bootstrapping a Neymann-Scott point process model
#'
#' Carries out a bootstrap for Neymann-Scott point process models
#' fitted by \link{fit.ns}().
#'
#' @return The first argument, with added information from the
#' bootstrap procedure.
#'
#' @param fit A fitted object from \link{fit.ns}().
#' @param rchild.fun A function for random number generation of the
#' number of children spawned by each parent. It must take two
#' arguments: The first argument must be \code{n}, the number of
#' random values to draw, and the second must be \code{child.par}, the
#' parameter specified to be estimated in the argument
#' \code{child.dist} argument to \link{fit.ns}(). The mean and
#' variance functions specified in this argument should be the
#' analytic mean and variance of the random numbers generated by
#' \code{rchild.fun}().
#' @param N The number of bootstrap resamples.
#' @param prog Logical, if \code{TRUE}, a progress bar is printed to
#' the console.
#' 
#' @export
boot.ns <- function(fit, rchild.fun, N, prog = TRUE){
    ## Extracting information.
    args <- fit$args    
    pars <- fit$pars
    n.pars <- length(pars)
    lims <- args$lims
    ## Error for fits with known (non-)siblings.
    if (!is.null(args$siblings)){
        stop("Bootstrapping not implemented for models with known (non-)siblings.")
    }
    boots <- matrix(0, nrow = N, ncol = n.pars)
    ## Setting up progress bar.
    if (prog){
        pb <- txtProgressBar(min = 0, max = N, style = 3)
    }
    for (i in 1:N){
        args$points <- sim.ns(pars = pars[c("D", "sigma")], lims = lims,
                              rchild = rchild.fun, child.par = pars["child.par"])
        args$sigma.sv <- pars["sigma"]
        args$child.dist$sv <- pars["child.par"]
        args$trace <- FALSE
        fit.boot <- do.call("fit.ns", args)
        boots[i, ] <- coef(fit.boot)
        ## Updating progress bar.
        if (prog){
            setTxtProgressBar(pb, i)
        }
    }
    if (prog){
        close(pb)
    }
    colnames(boots) <- names(pars)
    fit$boots <- boots
    fit$se <- apply(boots, 2, sd)
    class(fit) <- c("boot.nspp", class(fit))
    fit
}
