# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating distances between points subject to a buffer-zone edge correction.
#'
#' Calculates pairwise distances between points subject to a buffer-zone edge correction.
#'
#' @inheritParams fit.ns
#'
#' @export
buffer_distances <- function(points, lims, R) {
    .Call('nspp_buffer_distances', PACKAGE = 'nspp', points, lims, R)
}

#' Calculating distances between points subject to periodic boundary constraints.
#'
#' Calculates pairwise distances between points subject to periodic boundary constraints.
#'
#' @inheritParams fit.ns
#'
#' @export
pbc_distances <- function(points, lims) {
    .Call('nspp_pbc_distances', PACKAGE = 'nspp', points, lims)
}

